esphome:
  name: muinowatersensor
  friendly_name: muinowatersensor

esphome:
  name: muinowatersensor
  friendly_name: muinowatersensor
  external_components:
    - source:
        type: git
        url: https://github.com/martijnvwezel/watersensor.git
        ref: master
      components: [muinowatersensor]
    - source:
        type: local
        path: my_components

sensor:
  - platform: custom
    lambda: |-
      auto my_custom = new MyCustomSensor();
      App.register_component(my_custom);
      return {my_custom->water_liter_sensor};

  # * Make sure watermeter is able to be used in energy dashboard
    sensors:
      - name: "muino_water_liter"
        unit_of_measurement: L
        state_class: total
        device_class: water
        accuracy_decimals: 2

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino

# Enable logging
logger:
    hardware_uart: UART1

# Enable Home Assistant API
api:
  encryption:
    key: "let home assist create this"

ota:
  password: "create ota key in home assistant"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Muino Fallback Hotspot"
    password: "plkrn4565hfrd"

captive_portal:
